### ISSUE TITLE
trabalho-01

### ISSUE THREAD

**Issue by fsantanna** [schonmann/EDL#2]
Obrigado pela submissão.
Fiz alguns comentários, nada muito sério, mas seria bom colocar um exemplo mais representativo da linguagem (aquele exemplo em que a linguagem "vende").
Também seria bom passar um corretor ortográfico no texto.

**Comment by schonmann** [comment]
Farei as correções! Obrigado Professor.

**Comment by schonmann** [comment]
Correções:
- Ortografia.
- Melhores exemplos de código, explorando facilidades da linguagem Ruby.
- Avaliação comparativa mais aprofundada.
- Influência da linguagem Ada.
- Bibliografia atualizada.

**Comment by fsantanna** [comment]
Ficou bom, obrigado.
